### ISSUE TITLE
windows服务器报错

### ISSUE THREAD

**Issue by zhuxindong** [Aranxu/NodePanels#5]
windows服务器报错安装报错

![image](https://user-images.githubusercontent.com/24989246/160075741-9cfaacfe-73fd-473b-b67c-292161d0a2f6.png)

![image](https://user-images.githubusercontent.com/24989246/160075659-88444b7e-55cf-4a3b-afc4-de75ab5d2671.png)

**Comment by Aranxu** [comment]
请暂时手动选中指令复制，勿使用复制按钮，将于下版本修复
